#!/bin/python3

import math
import os
import random
import re
import sys

def sumXor(n):
    count=0
    if n==0:
        return 1
    for i in range(0,n):        
        if(n+i==n^i):
            count=count+1
    return count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    result = sumXor(n)

    fptr.write(str(result) + '\n')

    fptr.close()
